### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [jjangmes/northkorealy#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by jjangmes** [comment]
Thanks for the tip!

Got it working with <meta name="viewport" content="width=device-width, initial-scale=1">

Now it's mobile-friendly for sure.

**Comment by MarcoMorawec** [comment]
:+1: @jjangmes 

Make sure to close the issue, now that you've fixed everything :)
